language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"

env:
  - DJANGO=https://github.com/django/django/archive/master.tar.gz
  - DJANGO=https://github.com/django/django/archive/stable/1.6.x.tar.gz
  - DJANGO=https://github.com/django/django/archive/stable/1.5.x.tar.gz
  - DJANGO=https://github.com/django/django/archive/stable/1.4.x.tar.gz

install:
  - pip install $DJANGO
  - pip install -e .
  - pip install -r tests/requirements.txt

script:
  - ./tests/runtests.sh

matrix:
  exclude:
    - python: "3.2"
      env: DJANGO=https://github.com/django/django/archive/stable/1.4.x.tar.gz
    - python: "3.3"
      env: DJANGO=https://github.com/django/django/archive/stable/1.4.x.tar.gz
    - python: "2.6"
      env: DJANGO=https://github.com/django/django/archive/master.tar.gz
